package com.dudley.app.entities;

// Generated Feb 23, 2015 5:00:28 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "Company")
public class Company implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int companyId;
	private String companyName;
	private String companyDescription;
	private String stockTicker;
	private Set<CompanyFinancial> companyFinancials = new HashSet<CompanyFinancial>(0);
	private Set<PriceHistory> priceHistories = new HashSet<PriceHistory>(0);

	public Company() {
	}

	public Company(int companyId, String companyName,
			String stockTicker) {
		this.companyId = companyId;
		this.companyName = companyName;
		this.stockTicker = stockTicker;
	}

	public Company(int companyId, String companyName,
			String companyDescription, String stockTicker,
			Set<CompanyFinancial> companyFinancials, Set<PriceHistory> priceHistories) {
		this.companyId = companyId;
		this.companyName = companyName;
		this.companyDescription = companyDescription;
		this.stockTicker = stockTicker;
		this.companyFinancials = companyFinancials;
		this.priceHistories = priceHistories;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "company_id", unique = true, nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "company_name", nullable = false, length = 150)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "company_description", length = 300)
	public String getCompanyDescription() {
		return this.companyDescription;
	}

	public void setCompanyDescription(String companyDescription) {
		this.companyDescription = companyDescription;
	}

	@Column(name = "stock_ticker", nullable = false)
	public String getStockTicker() {
		return this.stockTicker;
	}

	public void setStockTicker(String stockTicker) {
		this.stockTicker = stockTicker;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	@Cascade({CascadeType.ALL})
	public Set<CompanyFinancial> getCompanyFinancials() {
		return this.companyFinancials;
	}

	public void setCompanyFinancials(Set<CompanyFinancial> companyFinancials) {
		this.companyFinancials = companyFinancials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	@Cascade({CascadeType.ALL})
	public Set<PriceHistory> getPriceHistories() {
		return this.priceHistories;
	}

	public void setPriceHistories(Set<PriceHistory> priceHistories) {
		this.priceHistories = priceHistories;
	}

}
