package com.dudley.app.entities;

// Generated Feb 23, 2015 5:00:28 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Type;
import org.joda.time.LocalDate;

/**
 * PriceHistory generated by hbm2java
 */
@Entity
@Table(name = "PriceHistory")
public class PriceHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int historyId;
	private Company company;
	private LocalDate priceDate;
	private Double closingPrice;
	private Double openPrice;
	private Double highPrice;
	private Double lowPrice;
	private Double volume;

	public PriceHistory() {
	}

	public PriceHistory(int historyId, Company company, LocalDate priceDate,
			Double closingPrice) {
		this.historyId = historyId;
		this.company = company;
		this.priceDate = priceDate;
		this.closingPrice = closingPrice;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "history_id", unique = true, nullable = false)
	public int getHistoryId() {
		return this.historyId;
	}

	public void setHistoryId(int historyId) {
		this.historyId = historyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id", nullable = false)
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "price_date", nullable = false)
	@Type(type = "org.jadira.usertype.dateandtime.joda.PersistentLocalDate")
	public LocalDate getPriceDate() {
		return this.priceDate;
	}

	public void setPriceDate(LocalDate priceDate) {
		this.priceDate = priceDate;
	}

	@Column(name = "closing_price", nullable = false, precision = 10, scale = 2)
	public Double getClosingPrice() {
		return closingPrice;
	}

	public void setClosingPrice(Double closingPrice) {
		this.closingPrice = closingPrice;
	}

	@Column(name = "open_price", nullable = true, precision = 10, scale = 2)
	public Double getOpenPrice() {
		return openPrice;
	}

	public void setOpenPrice(Double openPrice) {
		this.openPrice = openPrice;
	}

	@Column(name = "high_price", nullable = true, precision = 10, scale = 2)
	public Double getHighPrice() {
		return highPrice;
	}

	public void setHighPrice(Double highPrice) {
		this.highPrice = highPrice;
	}

	@Column(name = "low_price", nullable = true, precision = 10, scale = 2)
	public Double getLowPrice() {
		return lowPrice;
	}

	public void setLowPrice(Double lowPrice) {
		this.lowPrice = lowPrice;
	}

	@Column(name = "volume", nullable = true, precision = 15, scale = 2)
	public Double getVolume() {
		return volume;
	}

	public void setVolume(Double volume) {
		this.volume = volume;
	}

}
